% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Aug-2017 16:33:09
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('cov_across_time.mat');

cov_stackL = saveVarsMat.cov_stackL; % <225x96 double> too many elements

cov_stackR = saveVarsMat.cov_stackR; % <225x96 double> too many elements

clear saveVarsMat;
